// <auto-generated />
using System;
using HttpForge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HttpForge.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("HttpForge.Data.Entities.AppEnvironment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveGlobalSubsetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("HttpForge.Data.Entities.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveCollectionVariableSetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.CollectionFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("CollectionFolders");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.CollectionVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CollectionVariables");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.CollectionVariableEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionVariableSetId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectionVariableSetId");

                    b.ToTable("CollectionVariableEntries");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.CollectionVariableSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("CollectionVariableSets");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.EnvironmentVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppEnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppEnvironmentId");

                    b.ToTable("EnvironmentVariables");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.FormFieldItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HttpRequestItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HttpRequestItemId");

                    b.ToTable("FormFields");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.HeaderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HttpRequestItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HttpRequestItemId");

                    b.ToTable("Headers");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.HttpRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyContent")
                        .HasColumnType("TEXT");

                    b.Property<int>("BodyKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreTlsErrors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostScript")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PostScriptTrusted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("FolderId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.QueryParamItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HttpRequestItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HttpRequestItemId");

                    b.ToTable("QueryParams");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.RequestVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HttpRequestItemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HttpRequestItemId");

                    b.ToTable("RequestVariables");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.CollectionFolder", b =>
                {
                    b.HasOne("HttpForge.Data.Entities.Collection", "Collection")
                        .WithMany("Folders")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HttpForge.Data.Entities.CollectionFolder", "ParentFolder")
                        .WithMany("Children")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Collection");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.CollectionVariableEntry", b =>
                {
                    b.HasOne("HttpForge.Data.Entities.CollectionVariableSet", "VariableSet")
                        .WithMany("Entries")
                        .HasForeignKey("CollectionVariableSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VariableSet");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.CollectionVariableSet", b =>
                {
                    b.HasOne("HttpForge.Data.Entities.Collection", null)
                        .WithMany("VariableSets")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HttpForge.Data.Entities.EnvironmentVariable", b =>
                {
                    b.HasOne("HttpForge.Data.Entities.AppEnvironment", null)
                        .WithMany("Variables")
                        .HasForeignKey("AppEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HttpForge.Data.Entities.FormFieldItem", b =>
                {
                    b.HasOne("HttpForge.Data.Entities.HttpRequestItem", null)
                        .WithMany("FormFields")
                        .HasForeignKey("HttpRequestItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HttpForge.Data.Entities.HeaderItem", b =>
                {
                    b.HasOne("HttpForge.Data.Entities.HttpRequestItem", null)
                        .WithMany("Headers")
                        .HasForeignKey("HttpRequestItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HttpForge.Data.Entities.HttpRequestItem", b =>
                {
                    b.HasOne("HttpForge.Data.Entities.Collection", "Collection")
                        .WithMany("Requests")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HttpForge.Data.Entities.CollectionFolder", "Folder")
                        .WithMany("Requests")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Collection");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.QueryParamItem", b =>
                {
                    b.HasOne("HttpForge.Data.Entities.HttpRequestItem", null)
                        .WithMany("QueryParams")
                        .HasForeignKey("HttpRequestItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HttpForge.Data.Entities.RequestVariable", b =>
                {
                    b.HasOne("HttpForge.Data.Entities.HttpRequestItem", null)
                        .WithMany("Variables")
                        .HasForeignKey("HttpRequestItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HttpForge.Data.Entities.AppEnvironment", b =>
                {
                    b.Navigation("Variables");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.Collection", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("Requests");

                    b.Navigation("VariableSets");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.CollectionFolder", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.CollectionVariableSet", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("HttpForge.Data.Entities.HttpRequestItem", b =>
                {
                    b.Navigation("FormFields");

                    b.Navigation("Headers");

                    b.Navigation("QueryParams");

                    b.Navigation("Variables");
                });
#pragma warning restore 612, 618
        }
    }
}
